enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
patches-source = "revanced/revanced-patches" # where to fetch patches bundle from. default: "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli" # where to fetch cli from. default: "j-hc/revanced-cli"
# options like cli-source can also set per app
# rv-brand = "ReVanced Extended" # rebrand from 'ReVanced' to something different. default: "ReVanced"
patches-version = "latest" # 'latest', 'dev', or a version number. default: "latest"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = false
build-mode = "module"
arch = "arm64-v8a"
excluded-patches = ""
included-patches = ""
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" # fallback
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
enabled = false
build-mode = "module"
arch = "arm64-v8a"
version = "latest"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[googlephotos]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"
included-patches = ""
excluded-patches = ""

#[Twitch]
#enabled = false
#apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

# [Music-Extended]
# app-name = "Music"
# patches-source = "inotia00/revanced-patches"
# cli-source = "inotia00/revanced-cli"
# rv-brand = "ReVanced Extended"
# build-mode = "both"
# arch = "both"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

# [YouTube-Extended]
# app-name = "YouTube"
# patches-source = "inotia00/revanced-patches"
# cli-source = "inotia00/revanced-cli"
# rv-brand = "ReVanced Extended"
# build-mode = "both"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

# [Reddit-Extended]
# patches-source = "inotia00/revanced-patches"
# cli-source = "inotia00/revanced-cli"
# rv-brand = "ReVanced Extended"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Twitter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
build-mode = "apk"
dpi = "120-640dpi"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[TikTok]
enabled = false
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Messenger]
enabled = false
build-mode = "module"
arch = "arm64-v8a"
version = "latest"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.facebook.orca/"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[Facebook]
enabled = false
build-mode = "module"
arch = "arm64-v8a"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Strava]
build-mode = "module"
#arch = "arm64-v8a"
version = "381.12"
#dpi="120-640dpi"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps/strava-running-and-cycling-gps-385-14-release/strava-run-bike-hike-385-14-android-apk-download/"
#archive-dlurl = "https://archive.org/download/jhc-apksapkscom.stravacom.strava-385.14-all"
uptodown-dlurl = "https://strava.en.uptodown.com/android/"

[Instagram]
enabled = false
build-mode = "module"
arch = "arm64-v8a"
version = "latest"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.instagram.android"

[Yuka]
enabled = false
build-mode = "module"
dpi="120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

