enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
patches-source = "revanced/revanced-patches" # where to fetch patches bundle from. default: "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli" # where to fetch cli from. default: "j-hc/revanced-cli"
# options like cli-source can also set per app
# rv-brand = "ReVanced Extended" # rebrand from 'ReVanced' to something different. default: "ReVanced"
patches-version = "latest" # 'latest', 'dev', or a version number. default: "latest"


[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
version = "latest"
included-patches = "'MaterialYou'"
excluded-patches = "'GmsCore support'"
[googlephotos]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"
included-patches = ""
excluded-patches = ""
[Music]
build-mode = "module"
arch = "arm64-v8a"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
[Facebook]
build-mode = "module"
arch = "arm64-v8a"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
[Facebookmessenger]
build-mode = "module"
arch = "arm64-v8a"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
[Strava]
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
[Instagram]
build-mode = "module"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
[Yuka]
build-mode = "module"
arch = "universal"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
